# This is a basic workflow to help you get started with Actions

name: Issue Manager

on:
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/orgs/hft-rcpsp-scheduling/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: info / question, duplicate, wontfix, sub-task
          label-operator: NOT
